### ISSUE TITLE
Use environment variable NEOCITIES_API_KEY

### ISSUE THREAD

**Issue by mtusseau** [neocities/neocities-ruby#17]
First of all, thanks for your work: i just discovered and your scripts. I aim to use it for continuous inspection with Gitlab.

When using the command `neocities push <folder>` the script ignores the value stored in NEOCITIES_API_KEY: it uses the value stored in ~/.config/neocities/config.
For continuous integration reasons, it could be great if `neocities push` check that NEOCITIES_API_KEY is empty before loading the config file.

Best regards.

**Comment by nocko** [comment]
@kyledrake Will you please bump the gem version and push it out so we can use the client more easily for deploy via CI systems?

Then this issue can be closed. Thank you.

**Comment by kyledrake** [comment]
Apologies for the delay, this has been pushed. Thank you for fixing this!
