### ISSUE TITLE
Typo in 0.0.12 breaks push

### ISSUE THREAD

**Issue by nocko** [neocities/neocities-ruby#19]
undefined local variable or method `excluded_files'

https://github.com/neocities/neocities-ruby/blob/7dac5070dfc6794c1028a66d1f1f468a15f576f6/lib/neocities/cli.rb#L210

**Comment by nocko** [comment]
@kyledrake Rather urgent fix: 0.0.12 gem is broken for common usage pattern (file upload)

**Comment by a-vrma** [comment]
Yeah this is pretty urgent. You guys should start using rubocop.

**Comment by kyledrake** [comment]
Thanks for the fix, I've pushed 0.0.13. Hopefully it resolves this.
