### ISSUE TITLE
Push broken in Debian 9.3

### ISSUE THREAD

**Issue by mknepper** [neocities/neocities-ruby#3]
I've installed all the necessary gems, ran several updates and made sure Debian was up to date. This is the error I keep getting when I try to login.

`/var/lib/gems/2.3.0/gems/neocities-0.0.7/lib/neocities/cli.rb:70:in `run': undefined local variable or method `resp' for #<Neocities::CLI:0x0055adfb325ee8> (NameError)
Did you mean?  res`
`from /var/lib/gems/2.3.0/gems/neocities-0.0.7/bin/neocities:4:in '<top (required)>'`
`from /usr/local/bin/neocities:22:in 'load'
from /usr/local/bin/neocities:22:in '<main>'`

Not sure how to fix it? 

- Ruby is 2.3.0, installed
- Neocities is 0.0.7, installed

**_Edit:_
Replacing "resp" with "res" in the cli.rb source seems to fix the issue. Maybe update the source?**

**Comment by kyledrake** [comment]
Should be resolved now https://github.com/neocities/neocities-ruby/pull/2
