### ISSUE TITLE
Neocities CLI gitignore parsing

### ISSUE THREAD

**Issue by tatsumoto-ren** [neocities/neocities-ruby#33]
Hello. I have noticed that the Neocities CLI supports gitignore parsing. I have tried it, but it seems to incorrectly handle entries that start with a `/` and `!`. As you probably know, entries that start with a `/` tell git to ignore paths in the root directory of the repo, and entries that start with `!` negate previously defined rules for certain files. For example, to ignore my blog's drafts folder I would use a pattern that looks like this: `/blog/drafts`. Do you plan to extend support for gitignore parsing to fully comply with the actual gitignore files?

**Comment by Commenter25** [comment]
Please reopen this.

**Comment by tatsumoto-ren** [comment]
@Commenter25 Since you're interested, I made [bashcities](https://github.com/tatsumoto-ren/bashcities) to handle this and many other issues that I've faced over the years.
