### ISSUE TITLE
The CLI page on Neocities does not list dependency gems.

### ISSUE THREAD

**Issue by mknepper** [neocities/neocities-ruby#4]
There are a few gems that are dependencies, such as `res` that are not listed on the CLI page on Neocities. Users are stuck sorting through error messages in the CLI until they figure out which gems to install (that's how I found out `res` was needed). Possibly add a bit more description to the README.md and the Neocities CLI page?

**Comment by kyledrake** [comment]
Related to https://github.com/neocities/neocities-ruby/pull/2
