### ISSUE TITLE
No documentation for push --prune

### ISSUE THREAD

**Issue by chitinlink** [neocities/neocities-ruby#43]
There is no user-facing documentation for the `--prune` flag for the `push` command. I only found out about it through this repo... #30 #25

**Comment by chitinlink** [comment]
Also, it doesn't seem to be working..? files don't seem to get deleted at all using the command.

**Comment by Commenter25** [comment]
Prune is deleting files just fine for me.

**Comment by chitinlink** [comment]
After looking at your pull request, I realized I was using it wrong, I was running `neocities push <dir> --prune`, but the flag comes before the directory. It works fine for me.
