### ISSUE TITLE
The ability to pull, similar to the "git pull origin master" command.

### ISSUE THREAD

**Issue by mknepper** [neocities/neocities-ruby#5]
I would highly suggest users have the ability to pull their Neocities webpage if they need to instead of having to manually down the zip and extract it, or one page at a time. Using wget recursively can be a bit annoying.

**Comment by sysfu** [comment]
I just found and installed the neocities gem. It would be quite helpful to add a command option that pulled down all the web site files recursively. That way users who already have a somewhat extensively populated web directory can hit the ground running.

**Comment by wayword-dev** [comment]
This can probably be closed now that #49 is merged?
