### ISSUE TITLE
Push command throws error with new version 0.0.19

### ISSUE THREAD

**Issue by GrigorM** [neocities/neocities-ruby#50]
Just a headsup, the new update doesn't work well. I am running the `neocities push .` command via a gitlab ci job and I get this error:
```
internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- whirly (LoadError)
```

I had to revert to v0.0.17 to push my updates.

**Comment by kyledrake** [comment]
Should be working now, let me know if it isn't.
