### ISSUE TITLE
-e does not exclude folders

### ISSUE THREAD

**Issue by markdhughes** [neocities/neocities-ruby#7]
% neocities version
0.0.7
% neocities push -e ttf .

Expected: ttf folder is not uploaded
Got: Uploading ttf/FiraSans-UltraLightItalic.ttf ... EXISTS
etc.

**Comment by breakfast1** [comment]
Here is a solution: `paths.select {|p| !excluded_files.include?(Pathname.new(p).dirname.to_s) }`.

I'll make a pull request soon.

**Comment by kyledrake** [comment]
Will be fixed in 0.0.12, thank you!
